### ISSUE TITLE
Variables are ignored instead of stripped when there is no value assigned in the url

### ISSUE THREAD

**Issue by sandermanneke** [episodicza/ssgtm_filter_querystring#1]
When the page url contains a variable without a value assigned to it, it is ignored instead of removed.

For example: when logged_out is added as a blacklisted var then domain.com/somepage.html?dhw_logged_out would be ignored whilst domain.com/somepage.html?dhw_logged_out=1 will work as expected and be removed.

**Comment by sandermanneke** [comment]
Anyone reading this?

**Comment by skaaptjop** [comment]
Yes, thanks for that. I see what you mean. I'll work on fix quickly

**Comment by skaaptjop** [comment]
I ran the following test:
```
var mockData = {
  urlSource: "https://domain.com/somepage.html?dhw_logged_out",
  filterType: "blacklist",
  filterParams: [
    {name: "dhw_logged_out", caseSensitive: false}
  ]
};

let variableResult = runCode(mockData);
assertThat(variableResult).isEqualTo("https://domain.com/somepage.html");
```
and it passes.

Maybe I'm not 100% understanding you? Could you perhaps explain what you mean by "ignored"?

**Comment by sandermanneke** [comment]
Thank you - I tried that with my actual data and see that it passes also. 

Then I also checked GA4 and realised I am looking at the Page Referrer column when coming to this conclusion. 

The odd thing is that the whilst the "page referrer" also seemed to be cleaned by cleaning page_location I do still have these parameters in the urls whilst the other blacklisted ones are all accurately removed.

Anyway - not your problem it would seem. Sorry for disturbing and taking up your time. :-)

**Comment by skaaptjop** [comment]
> The odd thing is that the whilst the "page referrer" also seemed to be cleaned by cleaning page_location I do still have these parameters in the urls whilst the other blacklisted ones are all accurately removed.

So if you set `page_location` in the URL Source field then the blacklist also parses on the `page_referrer`?
That seems odd
